[package]
name = "clean-core"
version = "0.1.0"
authors = [ "Tim Steenvoorden <tim.steenvoorden@gmail.com>" ]
repository = "https://github.com/timjs/clean-core"

[dependencies.clean-stdenv]
version = "2.4.0"
path = "../clean-stdenv"

[dependencies.clean-generics]
version = "2.4.0"
path = "../clean-generics"

[library]
exposed-modules = [
    # Basic types
    "Bool",
    "Char",
    "Nat",
    "Int",
    "Real",
    "File",

    # Basic classes
    "Append",
    "Compare",
    "Enum",
    "Num",
    "Num.Bounded",
    "Num.Signed",
    "Show",

    # Basic macros
    "Function",

    # Arrays
    "Array",
    "Array.Strict",
    "Array.Unboxed",

    # Prelude
    "Core",
]
